### ISSUE TITLE
CS Engineering School webpage has a large gap below footer (design issue)

### ISSUE THREAD

**Issue by Farial-mahmod** [uweb/uw-footer#2]
**Description**: The link of CS Engineering School courses webpage (http://courses.cs.washington.edu/courses/csep531/) displays the footer in the middle of the webpage and below the footer there is a large gap.

**Tested On**:
1. Firefox on Windows 10
2. Chrome on Windows 10

**Solution**: Either populate the body of courses webpages with course details, or fix the footer at the bottom of each webpage.

**Screenshot** has been attached for better understanding.

![uw-gap-footer](https://github.com/uweb/uw-footer/assets/60639522/609fb9f9-5aa4-4c44-af19-fa880f2b7f47)

**Comment by lcaple** [comment]
The CSE website isn't using the footer in this codebase. Please contact CSE directly to give them this feedback.

**Comment by Farial-mahmod** [comment]
Would you provide a link to their repository or any system to report? Thank you.
